// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using SocialMediaManagement.Data;

namespace SocialMediaManagement.Migrations
{
    [DbContext(typeof(AppDbContext))]
    [Migration("20220317161749_Use identityuser in User model")]
    partial class UseidentityuserinUsermodel
    {
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("Relational:MaxIdentifierLength", 128)
                .HasAnnotation("ProductVersion", "5.0.12")
                .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

            modelBuilder.Entity("SocialMediaManagement.Models.Group", b =>
                {
                    b.Property<int>("GroupID")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<string>("GroupName")
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("GroupID");

                    b.ToTable("Groups");
                });

            modelBuilder.Entity("SocialMediaManagement.Models.GroupIActionRelation", b =>
                {
                    b.Property<int>("GroupIActionRelationID")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<int>("GroupID")
                        .HasColumnType("int");

                    b.Property<int>("ItemActionID")
                        .HasColumnType("int");

                    b.HasKey("GroupIActionRelationID");

                    b.HasIndex("GroupID");

                    b.HasIndex("ItemActionID");

                    b.ToTable("GroupIActionRelations");
                });

            modelBuilder.Entity("SocialMediaManagement.Models.GroupItemRelation", b =>
                {
                    b.Property<int>("GroupMenuItemRelationId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<int>("GroupID")
                        .HasColumnType("int");

                    b.Property<int>("ItemID")
                        .HasColumnType("int");

                    b.HasKey("GroupMenuItemRelationId");

                    b.HasIndex("GroupID");

                    b.HasIndex("ItemID");

                    b.ToTable("GroupItemRelations");
                });

            modelBuilder.Entity("SocialMediaManagement.Models.MenuItem", b =>
                {
                    b.Property<int>("ItemID")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<string>("Icon")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("ItemName")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("URL")
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("Visible")
                        .HasColumnType("int");

                    b.HasKey("ItemID");

                    b.ToTable("MenuItems");
                });

            modelBuilder.Entity("SocialMediaManagement.Models.MenuItemAction", b =>
                {
                    b.Property<int>("ItemActionID")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<string>("ItemActionName")
                        .HasColumnType("nvarchar(max)");

                    b.Property<int?>("MenuItemItemID")
                        .HasColumnType("int");

                    b.HasKey("ItemActionID");

                    b.HasIndex("MenuItemItemID");

                    b.ToTable("MenuItemActions");
                });

            modelBuilder.Entity("SocialMediaManagement.Models.User", b =>
                {
                    b.Property<int>("UserID")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<int>("AccessFailedCount")
                        .HasColumnType("int");

                    b.Property<string>("CompanyName")
                        .IsRequired()
                        .HasColumnType("nvarchar(100)");

                    b.Property<string>("ConcurrencyStamp")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Email")
                        .HasColumnType("nvarchar(max)");

                    b.Property<bool>("EmailConfirmed")
                        .HasColumnType("bit");

                    b.Property<string>("FirstName")
                        .IsRequired()
                        .HasColumnType("nvarchar(100)");

                    b.Property<int?>("GroupID")
                        .HasColumnType("int");

                    b.Property<string>("Id")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("LastName")
                        .IsRequired()
                        .HasColumnType("nvarchar(100)");

                    b.Property<bool>("LockoutEnabled")
                        .HasColumnType("bit");

                    b.Property<DateTimeOffset?>("LockoutEnd")
                        .HasColumnType("datetimeoffset");

                    b.Property<string>("NormalizedEmail")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("NormalizedUserName")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("PasswordHash")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("PhoneNumber")
                        .HasColumnType("nvarchar(max)");

                    b.Property<bool>("PhoneNumberConfirmed")
                        .HasColumnType("bit");

                    b.Property<string>("SecurityStamp")
                        .HasColumnType("nvarchar(max)");

                    b.Property<bool>("TwoFactorEnabled")
                        .HasColumnType("bit");

                    b.Property<string>("UserName")
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("UserID");

                    b.HasIndex("GroupID");

                    b.ToTable("Users");
                });

            modelBuilder.Entity("SocialMediaManagement.Models.GroupIActionRelation", b =>
                {
                    b.HasOne("SocialMediaManagement.Models.Group", "Group")
                        .WithMany("GroupIActionRelations")
                        .HasForeignKey("GroupID")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("SocialMediaManagement.Models.MenuItemAction", "MenuItemAction")
                        .WithMany("GroupIActionRelations")
                        .HasForeignKey("ItemActionID")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Group");

                    b.Navigation("MenuItemAction");
                });

            modelBuilder.Entity("SocialMediaManagement.Models.GroupItemRelation", b =>
                {
                    b.HasOne("SocialMediaManagement.Models.Group", "Group")
                        .WithMany("GroupItemRelations")
                        .HasForeignKey("GroupID")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("SocialMediaManagement.Models.MenuItem", "MenuItem")
                        .WithMany("GroupItemRelations")
                        .HasForeignKey("ItemID")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Group");

                    b.Navigation("MenuItem");
                });

            modelBuilder.Entity("SocialMediaManagement.Models.MenuItemAction", b =>
                {
                    b.HasOne("SocialMediaManagement.Models.MenuItem", "MenuItem")
                        .WithMany("MenuItemActions")
                        .HasForeignKey("MenuItemItemID");

                    b.Navigation("MenuItem");
                });

            modelBuilder.Entity("SocialMediaManagement.Models.User", b =>
                {
                    b.HasOne("SocialMediaManagement.Models.Group", "Group")
                        .WithMany("Users")
                        .HasForeignKey("GroupID");

                    b.Navigation("Group");
                });

            modelBuilder.Entity("SocialMediaManagement.Models.Group", b =>
                {
                    b.Navigation("GroupIActionRelations");

                    b.Navigation("GroupItemRelations");

                    b.Navigation("Users");
                });

            modelBuilder.Entity("SocialMediaManagement.Models.MenuItem", b =>
                {
                    b.Navigation("GroupItemRelations");

                    b.Navigation("MenuItemActions");
                });

            modelBuilder.Entity("SocialMediaManagement.Models.MenuItemAction", b =>
                {
                    b.Navigation("GroupIActionRelations");
                });
#pragma warning restore 612, 618
        }
    }
}
